name: LeaderSystem
main: com.ericlam.mc.leadersystem.main.LeaderSystem
version: ${project.version}
author: Hydranapse_
depend: [HyperNiteMC-Core]
softdepend: [PlaceholderAPI]
api-version: "1.15"
commands:
  leadersystem:
    aliases: [leadersys, leader, leaderboard]
    description: leadersystem command